/* Do not edit. File generated by rastro. */

#ifndef __AUTO_RASTRO_FILE_H__
#define __AUTO_RASTRO_FILE_H__
#include <rastro.h>

void rst_init_f_(int64_t *id1, int64_t *id2);
void rst_finalize_f_ (void);

#endif //__AUTO_RASTRO_FILE_H__
