/* Do not edit. File generated by rastro. */

#include "write1-gen.h"

/* Rastro function implementation for 'is' */
void rst_event_is_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, const char* s0)
{
  rst_startevent(ptr, type<<18|0x27100);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT_STR(ptr, s0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'is' - fortran support */
void rst_event_is_f_( int16_t *type, int32_t* i0, const char* s0)
{
  rst_event_is ((u_int16_t)* type, (u_int32_t)* i0,  s0);
}

/* Rastro function implementation for 'is' */
void rst_event_is_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, const char* s0)
{
  rst_startevent(ptr, type<<18|0x27100);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT_STR(ptr, s0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'is' - fortran support */
void rst_event_is_f_( int16_t *type, int32_t* i0, const char* s0)
{
  rst_event_is ((u_int16_t)* type, (u_int32_t)* i0,  s0);
}

/* Rastro function implementation for 'is' */
void rst_event_is_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, const char* s0)
{
  rst_startevent(ptr, type<<18|0x27100);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT_STR(ptr, s0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'is' - fortran support */
void rst_event_is_f_( int16_t *type, int32_t* i0, const char* s0)
{
  rst_event_is ((u_int16_t)* type, (u_int32_t)* i0,  s0);
}

/* Rastro function implementation for 'will' */
void rst_event_will_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int32_t i0, u_int64_t l0, u_int64_t l1)
{
  rst_startevent(ptr, type<<18|0x24475);
  RST_PUT(ptr, u_int64_t, l0);
  RST_PUT(ptr, u_int64_t, l1);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int16_t, w0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'will' - fortran support */
void rst_event_will_f_( int16_t *type, int16_t* w0, int32_t* i0, int64_t* l0, int64_t* l1)
{
  rst_event_will ((u_int16_t)* type, (u_int16_t)* w0, (u_int32_t)* i0, (u_int64_t)* l0, (u_int64_t)* l1);
}

/* Rastro function implementation for 'if' */
void rst_event_if_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, float f0)
{
  rst_startevent(ptr, type<<18|0x23700);
  RST_PUT(ptr, float, f0);
  RST_PUT(ptr, u_int32_t, i0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'if' - fortran support */
void rst_event_if_f_( int16_t *type, int32_t* i0, float* f0)
{
  rst_event_if ((u_int16_t)* type, (u_int32_t)* i0, (float)* f0);
}

/* Rastro function implementation for 'i' */
void rst_event_i_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0)
{
  rst_startevent(ptr, type<<18|0x27000);
  RST_PUT(ptr, u_int32_t, i0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'i' - fortran support */
void rst_event_i_f_( int16_t *type, int32_t* i0)
{
  rst_event_i ((u_int16_t)* type, (u_int32_t)* i0);
}

void rst_init_f_(int64_t *id1, int64_t *id2)
{
  rst_init((u_int64_t)* id1, (u_int64_t)* id2);
}
void rst_finalize_f_ ()
{
  rst_finalize();
}
